_clipboardSaver = [];

_1 = profileNamespace getVariable "rimmy_camp_var_FOBMarkerForDelete";
_2 = profileNamespace getVariable "rimmy_camp_var_recBuilding";
_3 = profileNamespace getVariable "rimmy_camp_var_recFOBAnchorLoc";
_4 = profileNamespace getVariable "rimmy_camp_var_recMine";
_5 = profileNamespace getVariable "rimmy_camp_var_recGroupLeaderSide";
_6 = profileNamespace getVariable "rimmy_camp_var_recGroupLocation";
_7 = profileNamespace getVariable "rimmy_camp_var_recGroupVehicle";
_8 = profileNamespace getVariable "rimmy_camp_var_recGroupLeaderType";
_9 = profileNamespace getVariable "rimmy_camp_var_recGroupCallsign";
_10 = profileNamespace getVariable "rimmy_camp_var_recGroupNumbers";
_11 = profileNamespace getVariable "rimmy_camp_var_recCrateCargo"; 
_12 = profileNamespace getVariable "rimmy_camp_var_recCrateLocation"; 
_13 = profileNamespace getVariable "rimmy_camp_var_recCrateBudget"; 
_14 = profileNamespace getVariable "rimmy_camp_var_recCrateStats"; 
_15 = profileNamespace getVariable "rimmy_camp_var_recFOBDeleteBlocker"; 
_16 = profileNamespace getVariable "rimmy_camp_var_slotLoadout"; 
_17 = profileNamespace getVariable "rimmy_camp_var_slotMedical";
_18 = profileNamespace getVariable "rimmy_camp_var_slotHunger";
_19 = profileNamespace getVariable "rimmy_camp_var_playerLoadout";  
_20 = profileNamespace getVariable "rimmy_camp_var_playerHunger"; 
_21 = profileNamespace getVariable "rimmy_camp_var_playerMedical";
_22 = profileNamespace getVariable "rimmy_camp_var_slotMarkers";

_clipboardSaver pushBack _1;
_clipboardSaver pushBack _2;
_clipboardSaver pushBack _3;
_clipboardSaver pushBack _4;
_clipboardSaver pushBack _5;
_clipboardSaver pushBack _6;
_clipboardSaver pushBack _7;
_clipboardSaver pushBack _8;
_clipboardSaver pushBack _9;
_clipboardSaver pushBack _10;
_clipboardSaver pushBack _11;
_clipboardSaver pushBack _12;
_clipboardSaver pushBack _13;
_clipboardSaver pushBack _14;
_clipboardSaver pushBack _15;
_clipboardSaver pushBack _16;
_clipboardSaver pushBack _17;
_clipboardSaver pushBack _18;
_clipboardSaver pushBack _19;
_clipboardSaver pushBack _20;
_clipboardSaver pushBack _21;
_clipboardSaver pushBack _22;

copyToClipboard str _clipboardSaver;